# -*- coding: utf-8 -*-
"""LLM_Features_and_NLP_Tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lfnJviX0J_UCv0s7Pgu_T_G_69ws4r2
"""

!pip install transformers

from transformers import pipeline
classifier = pipeline("sentiment-analysis")
classifier("I did bad in my exam")

from transformers import pipeline
classifier = pipeline("sentiment-analysis")
classifier("I met my crush today")

from transformers import pipeline
classifier = pipeline("sentiment-analysis")
classifier("I met my love today")

classifier = pipeline("zero-shot-classification")
classifier(
    "today is a election day",
    candidate_labels=["education","politics","business"],
)

classifier = pipeline("zero-shot-classification")
classifier(
    "today is a election day",
    candidate_labels=["sports","politics","business"],
)

classifier = pipeline("zero-shot-classification")
classifier(
    "today is a valemtines day",
    candidate_labels=["lovers","death","animals"],
)

generator = pipeline("text-generation")
generator("as of today, I did")

generator = pipeline("text-generation",model="sapientinc/HRM-Text-1B")
generator(
    "as of today, I did",
    max_length=20,
    num_return_sequences=3,
    )

generator = pipeline("fill-mask")
generator(
    "<mask> is king of forest "
)

from transformers import AutoTokenizer, AutoModelForQuestionAnswering
import torch

tokenizer = AutoTokenizer.from_pretrained("timpal0l/mdeberta-v3-base-squad2")
model = AutoModelForQuestionAnswering.from_pretrained("timpal0l/mdeberta-v3-base-squad2")

context = "i am from coimbatore,myself Gokila studying in KCE "
question = "what am i ?"

inputs = tokenizer(question, context, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)

answer_start_index = outputs.start_logits.argmax()
answer_end_index = outputs.end_logits.argmax() + 1

answer = tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(inputs["input_ids"][0][answer_start_index:answer_end_index]))
print(f"Question: {question}")
print(f"Context: {context}")
print(f"Answer: {answer}")

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-fr")
model = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-fr")

text_to_translate = "I am gokila from Coimbatore."

inputs = tokenizer(text_to_translate, return_tensors="pt")
outputs = model.generate(**inputs)
translated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(f"Original text: {text_to_translate}")
print(f"Translated text (French): {translated_text}")

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")

text_to_summarize = """Your task is to generate JSON. You are provided with a schema and an incomplete JSON instance. You must complete the JSON instance according to the schema. Do not output anything else. If a field's type is array, and the incomplete JSON does not already contain an array for this field, you can generate an empty array if there are no items to add. If a field's type is string, and the incomplete JSON does not already contain a string for this field, you can generate an empty string if there are no characters to add. Do not generate null values for required fields. Your entire response must be a valid JSON instance. The example responses are for illustrative purposes only, and may not fully conform to the schema as they are not used to generate JSON. However, your response must be valid JSON according to the schema.Your task is to generate JSON. You are provided with a schema and an incomplete JSON instance. You must complete the JSON instance according to the schema. Do not output anything else. If a field's type is array, and the incomplete JSON does not already contain an array for this field, you can generate an empty array if there are no items to add. If a field's type is string, and the incomplete JSON does not already contain a string for this field, you can generate an empty string if there are no characters to add. Do not generate null values for required fields. Your entire response must be a valid JSON instance. The example responses are for illustrative purposes only, and may not fully conform to the schema as they are not used to generate JSON. However, your response must be valid JSON according to the schema."""

# Encode the text
inputs = tokenizer(text_to_summarize, return_tensors="pt", max_length=1024, truncation=True)

# Generate summary
summary_ids = model.generate(
    inputs["input_ids"],
    num_beams=4,
    min_length=25,
    max_length=50,
    early_stopping=True,
    do_sample=False
)

summary_text = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print(f"Original text: {text_to_summarize[:200]}...")
print(f"Summary: {summary_text}")

from transformers import pipeline
generator = pipeline("ner")
generator(
    "my name is Gokila"
)

